STRINGS = {
    'tr': {
        # Steps
        'steps': ["Giriş", "Kişisel Bilgiler", "İş Deneyimi", "Eğitim", "Projeler", "Sertifikalar", "Beceriler", "İş İlanı Analizi", "Şablon Seçimi", "Tamamla"],

        # Step: Projects
        's_proj_info': "Önemli projelerinizi ekleyin (Okul, kişisel veya iş dışı).",
        's_proj_expander': "➕ / 🖊️ Proje Ekle veya Düzenle",
        's_proj_name': "Proje Adı",
        's_proj_tech': "Kullanılan Teknolojiler (Opsiyonel)",
        's_proj_desc': "Proje Detayları",
        's_proj_btn_add': "Proje Ekle",
        's_proj_btn_update': "Proje Güncelle",
        's_proj_list_header': "### Eklenen Projeler:",
        's_proj_no_item': "Henüz proje eklenmedi.",

        # Step: Certificates
        's_cert_info': "Sertifika ve eğitimlerinizi ekleyin.",
        's_cert_expander': "➕ / 🖊️ Sertifika Ekle veya Düzenle",
        's_cert_name': "Sertifika / Eğitim Adı",
        's_cert_auth': "Kurum / Kuruluş",
        's_cert_date': "Tarih",
        's_cert_btn_add': "Sertifika Ekle",
        's_cert_btn_update': "Güncelle",
        's_cert_list_header': "### Eklenen Sertifikalar:",
        's_cert_no_item': "Henüz sertifika eklenmedi.",
        
        # Sidebar
        'sidebar_manage_data': "💾 Verileri Yönet",
        'sidebar_download_backup': "📥 Yedeği İndir (JSON)",
        'sidebar_upload_backup': "📤 Yedeği Yükle",
        'sidebar_upload_success': "Veriler yüklendi!",
        'sidebar_upload_error': "Geçersiz dosya formatı.",
        
        # Step 0
        'intro_title': "👋 Merhaba!",
        'intro_desc_1': "Ben sizin <b>Yapay Zeka Destekli Kariyer Asistanınızım</b>.<br>Sizi <b>ATS (Aday Takip Sistemleri)</b> filtrelerinden geçirecek,<br>İK uzmanlarını etkileyecek profesyonel bir CV hazırlayalım.",
        'intro_bullet_1': "✅ <b>ATS Uyumlu Şablonlar</b>",
        'intro_bullet_2': "✅ <b>Akıllı İş İlanı Analizi</b>",
        'intro_bullet_3': "✅ <b>Otomatik Çeviri & Ön Yazı</b>",
        'intro_btn_start': "🚀 Hemen Başla",
        'lang_select_title': "🌍 Hangi dilde CV hazırlamak istersiniz?",
        'lang_select_desc': "Seçiminize göre CV içeriğinizin dili belirlenecektir.",
        'btn_back': "⬅️ Geri Dön",
        'btn_next': "İleri",
        'btn_prev': "Geri",
        
        # Step 1
        's1_info': "İletişim bilgilerinizi eksiksiz girin. ATS sistemleri sizi bu bilgilerle kaydeder.",
        's1_fullname': "Ad Soyad",
        's1_email': "E-posta",
        's1_phone': "Telefon",
        's1_city': "Şehir",
        's1_country': "Ülke",
        's1_linkedin': "LinkedIn URL",
        's1_github': "GitHub/Portfolio URL",
        's1_summary_label': "Profesyonel Özet (Kısa ve öz)",
        
        # Step 2
        's2_info': "En son deneyiminizden başlayarak ekleyin. İstediğiniz kadar ekleyebilirsiniz.",
        's2_expander': "➕ / 🖊️ Deneyim Ekle veya Düzenle",
        's2_job_title': "Unvan (Örn: Yazılım Mühendisi)",
        's2_company': "Şirket Adı",
        's2_start_date': "Kariyer Başlangıç",
        's2_end_date': "Kariyer Bitiş",
        's2_current_job': "Hala Devam Ediyor",
        's2_desc_label': "Açıklama / Başarılar",
        's2_desc_hint': "💡 ATS İpucu: Güçlü Fiiller Kullanın",
        's2_btn_add': "Listeye Ekle",
        's2_btn_update': "Güncelle",
        's2_btn_cancel_edit': "Düzenlemeyi İptal Et",
        's2_editing': "🖊️ Şuan Düzenleniyor:",
        's2_added_header': "### Eklenen Deneyimler:",
        's2_no_exp': "Henüz deneyim eklenmedi.",
        'btn_edit': "Düzenle",
        'btn_delete': "Sil",
        's2_btn_enhance': "✨ Cümlelerimi Güçlendir",
        
        # Step 3
        's3_info': "Eğitim bilgilerinizi ekleyin.",
        's3_expander': "➕ / 🖊️ Eğitim Ekle veya Düzenle",
        's3_school': "Okul / Üniversite",
        's3_degree': "Bölüm / Derece",
        's3_gpa': "GPA / Not Ortalaması (Opsiyonel)",
        's3_rank': "Derece / Başarı (Opsiyonel)",
        's3_rank_placeholder': "Örn: Bölüm 1.si, Onur Öğrencisi",
        's3_start_date': "Başlangıç",
        's3_end_date': "Mezuniyet (veya Beklenen)",
        's3_btn_add': "Eğitim Ekle",
        's3_btn_update': "Güncelle",
        's3_added_header': "### Eklenen Eğitimler:",
        's3_no_edu': "Henüz eğitim eklenmedi.",
        
        # Step 4
        's4_info': "Teknik becerilerinizi kategorilere ayırarak yazın.",
        's4_l1': "Programlama Dilleri",
        's4_l2': "Framework & Kütüphaneler",
        's4_l3': "Araçlar & Platformlar",
        's4_l4': "Diller (Yabancı Dil)",
        
        # Step 5
        's5_info': "Başvurmak istediğiniz iş ilanının metnini buraya yapıştırın. ATS uyumluluğunuzu test edelim.",
        's5_text_area': "İş İlanı Metni",
        's5_placeholder': "İlan detaylarını buraya yapıştırın...",
        's5_match_score': "Eşleşme Puanı",
        's5_btn_skip': "Analiz Yapmadan Geç (Atla)",
        's5_btn_analyze': "Sonuçlarla İlerle",
        
        # Step 6
        's6_info': "CV'niz için ATS uyumlu bir şablon seçin.",
        's6_classic_title': "### 🏛 Klasik",
        's6_classic_desc': "Geleneksel, ortalı başlık, standart boşluklar. En güvenli seçenek.",
        's6_modern_title': "### 🚀 Modern",
        's6_modern_desc': "Sola dayalı, temiz çizgiler, verimli alan kullanımı.",
        's6_academic_title': "### 🎓 Akademik",
        's6_academic_desc': "Yoğun içerik, minimal boşluk, teknik roller için ideal.",
        's6_btn_select': "Seç:",
        's6_selected_msg': "Seçilen Şablon:",
        
        # Step 7
        's7_success': "Tebrikler! CV'niz oluşturulmaya hazır.",
        's7_preview_title': "👁️ Canlı Önizleme",
        's7_preview_expander': "📄 PDF Önizlemesini Göster/Gizle",
        's7_raw_data_title': "### Veri Önizleme (JSON)",
        's7_raw_data_expander': "Ham Veriyi Gör",
        's7_download_title': "📥 CV'nizi İndir",
        's7_pdf_desc': "Profesyonel görünüm - İnsan okuyucular için",
        's7_docx_desc': "Maksimum ATS uyumluluğu - Düzenlenebilir",
        's7_btn_download_pdf': "📄 PDF İNDİR",
        's7_btn_download_docx': "📝 DOCX İNDİR",
        's7_trans_title': "🌍 İngilizce Versiyon",
        's7_trans_caption': "Verileriniz otomatik olarak İngilizce'ye çevrilir. Çeviriyi düzenleyebilirsiniz.",
        's7_btn_prepare_en': "🇬🇧 İngilizce Versiyonunu Hazırla",
        's7_success_trans': "Çeviri hazır! Aşağıdan düzenlemeleri yapabilirsiniz.",
        's7_expander_edit_en': "📝 İngilizce İçeriği Düzenle",
        's7_header_personal': "#### Kişisel Bilgiler",
        's7_header_exp': "#### Deneyimler",
        's7_header_edu': "#### Eğitim",
        's7_header_skills': "#### Beceriler",
        's7_btn_reset_trans': "🔄 Çeviriyi Sıfırla / Yeniden Çevir",
        's7_btn_download_en': "🇬🇧 PDF İNDİR (ENGLISH)",
        's7_tip': "💡 **İpucu:** Online başvurular için DOCX, e-posta veya bağımsız paylaşım için PDF kullanın.",
        's7_btn_restart': "Başa Dön",
        's7_translating': "Çeviri yapılıyor..."
    },
    
    'en': {
        # Steps
        'steps': ["Intro", "Personal Info", "Experience", "Education", "Projects", "Certifications", "Skills", "Job Analysis", "Template Selection", "Finish"],
        
        # Step: Projects
        's_proj_info': "Add your significant projects (Academic, personal, or freelance).",
        's_proj_expander': "➕ / 🖊️ Add or Edit Project",
        's_proj_name': "Project Name",
        's_proj_tech': "Technologies Used (Optional)",
        's_proj_desc': "Project Details",
        's_proj_btn_add': "Add Project",
        's_proj_btn_update': "Update Project",
        's_proj_list_header': "### Added Projects:",
        's_proj_no_item': "No projects added yet.",
        
        # Step: Certificates
        's_cert_info': "Add your certifications and trainings.",
        's_cert_expander': "➕ / 🖊️ Add or Edit Certificate",
        's_cert_name': "Certificate / Course Name",
        's_cert_auth': "Organization / Authority",
        's_cert_date': "Date",
        's_cert_btn_add': "Add Certificate",
        's_cert_btn_update': "Update",
        's_cert_list_header': "### Added Certifications:",
        's_cert_no_item': "No certifications added yet.",
        
        # Sidebar
        'sidebar_manage_data': "💾 Manage Data",
        'sidebar_download_backup': "📥 Download Backup (JSON)",
        'sidebar_upload_backup': "📤 Upload Backup",
        'sidebar_upload_success': "Data loaded successfully!",
        'sidebar_upload_error': "Invalid file format.",
        
        # Step 0
        'intro_title': "👋 Hello!",
        'intro_desc_1': "I am your <b>AI Powered Career Assistant</b>.<br>Let's create a professional CV that passes <b>ATS (Applicant Tracking Systems)</b> filters and impresses HR specialists.",
        'intro_bullet_1': "✅ <b>ATS Friendly Templates</b>",
        'intro_bullet_2': "✅ <b>Smart Job Description Analysis</b>",
        'intro_bullet_3': "✅ <b>Auto Translation & Cover Letter</b>",
        'intro_btn_start': "🚀 Start Now",
        'lang_select_title': "🌍 Which language would you like to prepare your CV in?",
        'lang_select_desc': "The content of your CV will be determined by your selection.",
        'btn_back': "⬅️ Go Back",
        'btn_next': "Next",
        'btn_prev': "Back",
        
        # Step 1
        's1_info': "Enter your contact details completely. ATS systems register you with this information.",
        's1_fullname': "Full Name",
        's1_email': "Email",
        's1_phone': "Phone",
        's1_city': "City",
        's1_country': "Country",
        's1_linkedin': "LinkedIn URL",
        's1_github': "GitHub/Portfolio URL",
        's1_summary_label': "Professional Summary (Short and concise)",
        
        # Step 2
        's2_info': "Add starting from your most recent experience. You can add as many as you want.",
        's2_expander': "➕ / 🖊️ Add or Edit Experience",
        's2_job_title': "Job Title (e.g. Software Engineer)",
        's2_company': "Company Name",
        's2_start_date': "Start Date",
        's2_end_date': "End Date",
        's2_current_job': "Currently Working Here",
        's2_desc_label': "Description / Achievements",
        's2_desc_hint': "💡 ATS Tip: Use Strong Action Verbs",
        's2_btn_add': "Add to List",
        's2_btn_update': "Update",
        's2_btn_cancel_edit': "Cancel Editing",
        's2_editing': "🖊️ Currently Editing:",
        's2_added_header': "### Added Experiences:",
        's2_no_exp': "No experience added yet.",
        'btn_edit': "Edit",
        'btn_delete': "Delete",
        's2_btn_enhance': "✨ Enhance My Sentences",
        
        # Step 3
        's3_info': "Add your education details.",
        's3_expander': "➕ / 🖊️ Add or Edit Education",
        's3_school': "School / University",
        's3_degree': "Degree / Department",
        's3_gpa': "GPA (Optional)",
        's3_rank': "Rank / Honor (Optional)",
        's3_rank_placeholder': "e.g. Valedictorian, Dean's List",
        's3_start_date': "Start Date",
        's3_end_date': "Graduation (or Expected)",
        's3_btn_add': "Add Education",
        's3_btn_update': "Update",
        's3_added_header': "### Added Education:",
        's3_no_edu': "No education added yet.",
        
        # Step 4
        's4_info': "List your technical skills by category.",
        's4_l1': "Programming Languages",
        's4_l2': "Frameworks & Libraries",
        's4_l3': "Tools & Platforms",
        's4_l4': "Languages (Foreign)",
        
        # Step 5
        's5_info': "Paste the job description you want to apply for. Let's test your ATS compatibility.",
        's5_text_area': "Job Description Text",
        's5_placeholder': "Paste job details here...",
        's5_match_score': "Match Score",
        's5_btn_skip': "Skip Analysis",
        's5_btn_analyze': "Proceed with Results",
        
        # Step 6
        's6_info': "Choose an ATS-friendly template for your CV.",
        's6_classic_title': "### 🏛 Classic",
        's6_classic_desc': "Traditional, centered header, standard spacing. The safest choice.",
        's6_modern_title': "### 🚀 Modern",
        's6_modern_desc': "Left-aligned, clean lines, efficient space usage.",
        's6_academic_title': "### 🎓 Academic",
        's6_academic_desc': "Dense content, minimal whitespace, ideal for technical roles.",
        's6_btn_select': "Select:",
        's6_selected_msg': "Selected Template:",
        
        # Step 7
        's7_success': "Congratulations! Your CV is ready to be generated.",
        's7_preview_title': "👁️ Live Preview",
        's7_preview_expander': "📄 Show/Hide PDF Preview",
        's7_raw_data_title': "### Data Preview (JSON)",
        's7_raw_data_expander': "See Raw Data",
        's7_download_title': "📥 Download Your CV",
        's7_pdf_desc': "Professional look - For human readers",
        's7_docx_desc': "Maximum ATS compatibility - Editable",
        's7_btn_download_pdf': "📄 DOWNLOAD PDF",
        's7_btn_download_docx': "📝 DOWNLOAD DOCX",
        's7_trans_title': "🌍 English Version",
        's7_trans_caption': "Your data is automatically translated to English. You can edit the translation.",
        's7_btn_prepare_en': "🇬🇧 Prepare English Version",
        's7_success_trans': "Translation ready! You can edit below.",
        's7_expander_edit_en': "📝 Edit English Content",
        's7_header_personal': "#### Personal Info",
        's7_header_exp': "#### Experience",
        's7_header_edu': "#### Education",
        's7_header_skills': "#### Skills",
        's7_btn_reset_trans': "🔄 Reset / Re-translate",
        's7_btn_download_en': "🇬🇧 DOWNLOAD PDF (ENGLISH)",
        's7_tip': "💡 **Tip:** Use DOCX for online applications, PDF for email or direct sharing.",
        's7_btn_restart': "Start Over",
        's7_translating': "Translating..."
    }
}
